### ISSUE TITLE
JSC_TRAILING_COMMA in `InteractionEvents`

### ISSUE THREAD

**Issue by jochenberger** [bpmn-io/bower-bpmn-js#4]
There's a trailing comma in `bpmn-viewer.js:12141`
```javascript
  var bindings = {
    mouseover: 'element.hover',
    mouseout: 'element.out',
    click: 'element.click',
    dblclick: 'element.dblclick',
    mousedown: 'element.mousedown',
    mouseup: 'element.mouseup', // <-
  };
```
This will cause issues in IE8 and prevents minification with Google Closure Compiler.

**Comment by jochenberger** [comment]
And another one in moddle:

```javascript
var BUILTINS = {
  String: true,
  Boolean: true,
  Integer: true,
  Real: true,
  Element: true
};
```

**Comment by nikku** [comment]
We will provide a patch release for this. Any other findings that fall in the same category?

**Comment by nikku** [comment]
The comma issues will be fixed in v0.9.1 of our library.

**Comment by jochenberger** [comment]
Looks good, thanks. I haven't found any other issues yet, but JS[HL]int should be able to detect those things.

**Comment by nikku** [comment]
We run it in es5 mode (which is the default). It allows trailing commas and thus does not fail on these issues. Did you manage to get  our library running on IE8?

**Comment by jochenberger** [comment]
Actually, I haven't tried. Officially, we don't support IE8, but this caused errors during minification (which we do in ES3 mode).

**Comment by nikku** [comment]
I would have been surprised to hear something positive about IE8 + bpmn-js, too.

Thanks for your findings.
